### PR TITLE
Override msg patch + other tiny stuff

### PR DESCRIPTION
**Pull request by bonastreyair**
- Override of the messages done! (even the passthru!)
- Added .eslintrc (hope it works for you this file) (I see that you are using 4 spaces and standard js uses 2...) and `GitHub` can't keep up on those kind of changes very easily...
- Added modifications on `CHANGELOG`
- Upgraded to `v2.0.3 coco-ssd` npm package
- Solved async issues when many images arrived at the same time to the node (make use of better variable creation (using `let`, `const` and `var`)

I've seen the new changes on the `model.load`  for the `coco-ssd` using the `file://`, it is much simpler this way, I agree. I didn't know you could make use of `file://` to refer to the installed node package. 

It seems it can't automatically merge... it is weird since I have merged your changes...

### CODE REVIEW

**Comment by bonastreyair** [comment]
I will merge the changes that you are doing now in a while, so that we don't interfere each other. Let me know when you are done to integrate the additions I prepared with this new PR.

**Comment by bonastreyair** [comment]
Now it is ready to merge I've added all your latests changes, I've also tested them and it works fine.

I've added back dependancy libraries `express` and `compression` in the `package.json`.

**Comment by bonastreyair** [comment]
As you may see I left the float value as is, I didn't understand why the use of 
```js
Math.round(results[i].probability * 10000)/10000
```
Since the probability result was still a `float` like at the beginning but with less precision.

**Comment by dceejay** [comment]
most excellent - really starting to look good. Many thanks for all your effort.

**Comment by bonastreyair** [comment]
> most excellent - really starting to look good. Many thanks for all your effort.

Thanks! That means a lot to me!

**Comment by dceejay** [comment]
> Since the probability result was still a float like at the beginning but with less precision.

are you telling me these model are accurate to more than 3 decimal places ? Thats like a cheap digital thermometer saying it's 22.312345 degrees C  - totally meaningless.

**Comment by bonastreyair** [comment]
Haha no, you are totally right, but for the same reason, what’s the point on doing some calculations on that value reducing the decimals?  It is just a float.

**Comment by dceejay** [comment]
because the next thing people always do is display it in a table as it it were gospel, so we may as well trim it while we iterate the table rather than make someone else have to do it again later. :-)

**Comment by bonastreyair** [comment]
> because the next thing people always do is display it in a table as it it were gospel, so we may as well trim it while we iterate the table rather than make someone else have to do it again later. :-)

My opinion is that then "its their problem" to add a `(100*score).toFixed(2)` to convert the float and change it into a text to show it in a table (if that is their application). I would leave it as a pure float, because it is the real output of the neural network and because it is more efficient than trimming it or converting it into a text. But it is is up to you (its just my humble opinion) 😃

**Comment by dceejay** [comment]
suppose so - to my mind it gives a false impression of "confidence" that is not warranted.

**Pull request merged**
