### PR TITLE
addition of tf mobilenets node + general code overhaul 

### PR DESCRIPTION
**Pull request by bonastreyair**
It seems that at the end I've changed so many things that `GitHub` can't keep up where are the changes that I made. Hope you can check them all. Hope you like them and accept the PR. 😊

Here is the `CHANGELOG` (I updated it to `v0.2.0` in the `package.json`, but it can truly be `v1.0.0` since it is a big overhaul change, you will see why...)

# Changelog
### Added
 - New `tf mobilenets` node
 - Standarized node status defined globally for all nodes
 - `JavaScript` code has been standarized following [Standard JS](https://standardjs.com/index.html)
 - Badges in `README` (platform Node-RED, code style, licence)
 - `CHANGELOG` file
 - New contributor `Yair Bonastre` in `package.json`
 - `google` keyword to `package.json` 

### Changed
 - General polish `JavaScript` code across all nodes
 	- Variable names
 	- Refining general reusable functions
 - Tensorflow node logo updated to 2.0
 - Node color matches official Tensorflow orange color
 - Node-RED example (improved)
 - Better icons in nodes configuration
 - Standard configuration templates
 - Revised information help menus 
 - Name of npm module to `node-red-contrib-tfjs-nodes` and its description
 - JavaScript file from `tfjs.js` to `tfjs-nodes.js`

### Fixed
 - Correct model initial loading for `tf coco ssd` node 

### Removed
 - Dependancies from `express` and `compression` npm modules
 - Local load of `coco ssd` model - will come back on a future release
 - Override messages - will come back on a future release

### CODE REVIEW

**Comment by dceejay** [comment]
I won't accept it because you have removed the local model. That is one of the main features of this node - that it will work without an internet connection...

**Comment by bonastreyair** [comment]
No worries I'm adding it now 😄

**Comment by dceejay** [comment]
Hi - I also realised you added to this project rather than the separated coco-ssd one (https://github.com/dceejay/tfjs-coco-ssd) - that is more recent - so I updated the one in here to match that. (hence new conflicts above)... but yes this is a better place for this work.

**Comment by bonastreyair** [comment]
There you go! Now with `Online` and `Local` options. For now just working for `tf coco ssd` node. I bumped to `v1.0.0` 😄 . 

# Changelog
### Added
 - New `tf mobilenets` node
 - Standarized node status defined globally for all nodes
 - `JavaScript` code has been standarized following [Standard JS](https://standardjs.com/index.html)
 - Badges in `README` (platform Node-RED, code style, licence)
 - `CHANGELOG` file
 - New contributor `Yair Bonastre` in `package.json`
 - `google` keyword to `package.json` 
 - New `Parameters` section in configuration
 - Added `Online` and `Local` options for all nodes (`tf coco ssd` is the only supported for now)

### Changed
 - General polish `JavaScript` code across all nodes
 	- Variable names
 	- Refining general reusable functions
 - Tensorflow node logo updated to 2.0
 - Node color matches official Tensorflow orange color
 - Node-RED example (improved)
 - Better icons in nodes configuration
 - Standard configuration templates
 - Revised information help menus 
 - Name of npm module to `node-red-contrib-tfjs-nodes` and its description
 - JavaScript file from `tfjs.js` to `tfjs-nodes.js`
 - Set all used libraries to `const` variables
 - `Min. Threshold` and `Max. Detections` are now selected from an easier spinner
 - `Min. Threshold` is now defined from 0 to 100 in %

### Fixed
 - Correct model initial loading for `tf coco ssd` node 

### Removed
 - Dependancies from `express` and `compression` npm modules
 - Override of messages properties - will come back on a future release

**Review by bonastreyair — COMMENTED** [review]
Did you check/tested the changes? Did you like them?

**Comment by dceejay** [comment]
Yes still some work to do before release (like re-add overrides - and the local model doesn't load correctly for me - and would be nice to try and make all models report back same properties  - but yes can see how you are trying to make them consistent. So have merged and can work in master.

**Comment by bonastreyair** [comment]
Awesome! I can re-add overrides easily today, not a big deal I can make another PR for that.

What concerns me is the loading of local model, it works for me if I run `node-red` from the `/Users/username/` directory. I'm on a Mac, didn't test it on Windows though...

Maybe it would be better to have a 100% configurable element where you can define the exact path tot the file instead of trying to build the automatic path...

**Comment by dceejay** [comment]
no worries - I can sort the pathing. Also in "my other coco node" - I have added option for image passthrough to save splitting / cloning the flow path which saves time and memory... - and also am looking at tf.dispose to also tidy up after processing to save memory.

**Comment by bonastreyair** [comment]
OK! Then I'll be waiting for the next release!

Check out that `tensorflow` has recently released `@tensorflow-models/coco-ssd:2.0.3`. It seems they have [fixed a memory leak](https://github.com/tensorflow/tfjs-models/releases/tag/coco-ssd-v2.0.3). I have tested it with this new version and it works fine for me (global and local). Maybe you could also upgrade this node package to the latest version in your next release. 😄 

I'm here if you need any clarifications on the proposed unification and consistency of the code. Also I'm no `JavaScript` expert nor `HTML` expert, so there might be not best practices. I did my best.

**Comment by dceejay** [comment]
I'll let you re-add the overrides though :-)...
Also can you add the necessary .eslintrc file you are using as my default for other projects is not this. If not i will revert it.

**Comment by bonastreyair** [comment]
Sure! I'll do the overrides! It is quite simple.

What do you mean with `.eslintrc` file? You refer to [ESLint](https://eslint.org/docs/user-guide/getting-started)? First time I hear of it, yeah sure I will add this file.

I used [Standard JS](https://standardjs.com/) which doesn't need this '.eslintrc' file, that's why there was no such file.

**Comment by dceejay** [comment]
I use vscode editor so it picks up the .eslintrc file or .jshintrc or .jscsrc - either would do. I don't really want to do an `npm install standard --save-dev` into this project.

Meanwhile I fixed the local load for coco and added passthru and tf-dispose... - maybe want to replicate those across others ? What do you think ?

**Comment by dceejay** [comment]
OK - having played around some more - I think I'm also going to revert the local/online mode option - using express locally is much faster to reload the model than using file: option. Also the mobilenet forces you to use tfconv (to convert the model) and that refuses to allow local file loading. Using express allows offline mobilenet usage.

**Comment by bonastreyair** [comment]
> I use vscode editor so it picks up the .eslintrc file or .jshintrc or .jscsrc - either would do. I don't really want to do an `npm install standard --save-dev` into this project.

Sure! I just use `standard` to check the code + beautify, it is not included in the project.

> Meanwhile I fixed the local load for coco and added passthru and tf-dispose... - maybe want to replicate those across others ? What do you think ?

Great!, yeah I would add it across others just in case of future memory leak...

**Comment by bonastreyair** [comment]
> OK - having played around some more - I think I'm also going to revert the local/online mode option - using express locally is much faster to reload the model than using file: option. Also the mobilenet forces you to use tfconv (to convert the model) and that refuses to allow local file loading. Using express allows offline mobilenet usage.

When I used the `express` library it never worked at `Node-RED` first boot + deploy, after another deployment then it worked. Local load is super fast on my computer... don't know what difference of speed you are having with yours. (I just tried to remove as many dependancies as possible)

I didn't know about mobilenets local usage, I though it would work the same way as in the `tf coco ssd`, I haven't made enough research, it was a `TODO`, so feel free to change it, you are the expert here. 😄 

I finished adding the overrides on the `msg` , also improved a bit some of the code since the async was causing a bit of trouble with variables when many nodes send simultaneous information to the same node, now it is solved! I will send the new PR very soon.

**Pull request merged**
